In [1]:
data = [
    {'place': 'Tokyo', 'sum': 1500, 'color': 'red'},
    {'place': 'Osaka', 'sum': 1200, 'color': 'blue'},
    {'place': 'Nagoya', 'sum': 500, 'color': 'green'},
    {'place': 'Yokohama', 'sum': 700, 'color': 'red'},
    {'place': 'Fukuoka', 'sum': 500, 'color': 'blue'},
    {'place': 'Kyoto', 'sum': 500, 'color': 'blue'},
]

# One Hot 化
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer(dtype=int)
data_vec = vec.fit_transform(data)

# 変換した特徴量の名前
print(vec.get_feature_names())
# 変換結果(疎行列の形式)
print(data_vec)
# 変換結果(np.arrayにして見やすく)
print(data_vec.toarray())

['color=blue', 'color=green', 'color=red', 'place=Fukuoka', 'place=Kyoto', 'place=Nagoya', 'place=Osaka', 'place=Tokyo', 'place=Yokohama', 'sum']
  (0, 2)	1
  (0, 7)	1
  (0, 9)	1500
  (1, 0)	1
  (1, 6)	1
  (1, 9)	1200
  (2, 1)	1
  (2, 5)	1
  (2, 9)	500
  (3, 2)	1
  (3, 8)	1
  (3, 9)	700
  (4, 0)	1
  (4, 3)	1
  (4, 9)	500
  (5, 0)	1
  (5, 4)	1
  (5, 9)	500
[[   0    0    1    0    0    0    0    1    0 1500]
 [   1    0    0    0    0    0    1    0    0 1200]
 [   0    1    0    0    0    1    0    0    0  500]
 [   0    0    1    0    0    0    0    0    1  700]
 [   1    0    0    1    0    0    0    0    0  500]
 [   1    0    0    0    1    0    0    0    0  500]]
