In [5]:
import numpy as np 
from sklearn import preprocessing
data = np.array([1, 2, 3, 1, 4, 2, 5, 1])
# OneHotEncoder()の入力は2次元配列でなければいけない。
data = data.reshape(-1, 1)

enc = preprocessing.OneHotEncoder()
data_encoded = enc.fit_transform(data)
print(enc.get_feature_names())
print(data_encoded.toarray())


['x0_1' 'x0_2' 'x0_3' 'x0_4' 'x0_5']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
